### ISSUE TITLE
Export on OS X fails

### ISSUE THREAD

**Issue by ninjamode** [processing/processing-experimental#33]
I cant export to *.app, seems the .icns icon file is missing.
Works fine in normal java mode.

Exact error:

```
java.io.FileNotFoundException: /Users/name/Documents/Processing/modes/ExperimentalMode/application/sketch.icns (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:146)
    at processing.app.Base.copyFile(Base.java:2587)
    at processing.mode.java.JavaBuild.exportApplication(JavaBuild.java:1227)
    at processing.mode.java.JavaBuild.exportApplication(JavaBuild.java:1138)
    at processing.mode.java.JavaMode.handleExportApplication(JavaMode.java:166)
    at processing.mode.java.JavaEditor.exportApplicationPrompt(JavaEditor.java:418)
    at processing.mode.java.JavaEditor.handleExportApplication(JavaEditor.java:239)
    at processing.mode.java.JavaToolbar.handlePressed(JavaToolbar.java:122)
    at processing.app.EditorToolbar.mousePressed(EditorToolbar.java:474)
    at java.awt.Component.processMouseEvent(Component.java:6502)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3320)
    at java.awt.Component.processEvent(Component.java:6270)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4861)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4489)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:708)
    at java.awt.EventQueue$4.run(EventQueue.java:706)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by Manindra29** [comment]
Seems like I missed adding that file. Are you running the latest version of PDE X?

**Comment by ninjamode** [comment]
I think so. I'm running processing 2.1, and I just installed PDE X some days ago. Is there some place where I can see which version I'm running?

**Comment by Manindra29** [comment]
I think I never added that option. Lol. Yes you must be running the latest version then.

**Comment by Manindra29** [comment]
Okay, this has been fixed for the next release. For the time being, you can copy the `application` folder from `Processing.app/Contents/Java/modes/java/` folder to `<your sketch book folder>/modes/ExperimentalMode/`. Basically replace Experimental Mode's application folder.
