### ISSUE TITLE
Sketch Outline

### ISSUE THREAD

**Issue by knupel** [processing/processing-experimental#50]
Sorry, 
I don't know where I can post this about Sketch outline, so I post here.
Sketch outline crash when it's use a incompatible code in the sketch like that : The class diewald.p5gui.GUI is incompatible with Processing 2.0.  see below
But the sketch work. And important I don't import this Library

Sketch Outline Tool - Oops. Something went wrong with buildTree() :P java.lang.IllegalArgumentException: Comparison method violates its general contract!
java.lang.IllegalArgumentException: Comparison method violates its general contract!
    at java.util.TimSort.mergeHi(TimSort.java:868)
    at java.util.TimSort.mergeAt(TimSort.java:485)
    at java.util.TimSort.mergeCollapse(TimSort.java:408)
    at java.util.TimSort.sort(TimSort.java:214)
    at java.util.TimSort.sort(TimSort.java:173)
    at java.util.Arrays.sort(Arrays.java:659)
    at java.util.Collections.sort(Collections.java:217)
    at sketchoutline.tool.TreeMaker.sortTree(Unknown Source)
    at sketchoutline.tool.TreeMaker.sortTree(Unknown Source)
    at sketchoutline.tool.TreeMaker.buildTree(Unknown Source)
    at sketchoutline.tool.TreeMaker.<init>(Unknown Source)
    at sketchoutline.tool.ThreadedTreeMaker.<init>(Unknown Source)
    at sketchoutline.tool.SketchOutlineFrame.<init>(Unknown Source)
    at sketchoutline.tool.SketchOutline$1.run(Unknown Source)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Outline couldn't be created :( 
The sketch may have compilation errors.
Tool opened: Scene_25 - TabManager
The class diewald.p5gui.GUI is incompatible with Processing 2.0.
A library (or other code) is using registerMouseEvent() which is no longer available.
A library (or other code) is using registerKeyEvent() which is no longer available.

Tool closed: Scene_25 - TabManager
Sketch Outline 0.1.7 (beta)
By - Manindra Moharana | http://www.mkmoharana.com/
Sketch Outline Tool - Oops. Something went wrong with buildTree() :P java.lang.IllegalArgumentException: Comparison method violates its general contract!
java.lang.IllegalArgumentException: Comparison method violates its general contract!
    at java.util.TimSort.mergeHi(TimSort.java:868)
    at java.util.TimSort.mergeAt(TimSort.java:485)
    at java.util.TimSort.mergeCollapse(TimSort.java:408)
    at java.util.TimSort.sort(TimSort.java:214)
    at java.util.TimSort.sort(TimSort.java:173)
    at java.util.Arrays.sort(Arrays.java:659)
    at java.util.Collections.sort(Collections.java:217)
    at sketchoutline.tool.TreeMaker.sortTree(Unknown Source)
    at sketchoutline.tool.TreeMaker.sortTree(Unknown Source)
    at sketchoutline.tool.TreeMaker.buildTree(Unknown Source)
    at sketchoutline.tool.TreeMaker.<init>(Unknown Source)
    at sketchoutline.tool.ThreadedTreeMaker.<init>(Unknown Source)
    at sketchoutline.tool.SketchOutlineFrame.<init>(Unknown Source)
    at sketchoutline.tool.SketchOutline$1.run(Unknown Source)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Outline couldn't be created :( 
The sketch may have compilation errors.

**Comment by Manindra29** [comment]
Issues with Sketch Outline tool should be reported at https://github.com/Manindra29/Sketch-Outline/

As it has been integrated into PDE X, I'm no longer actively developing it as a separate tool.
